### ISSUE TITLE
errore "fopen(): Unable to open ssh2.sftp://Resource id

### ISSUE THREAD

**Issue by danp86** [OpenAccess-Italia/ComplianceGuard#10]
Buongiono,
inseguito alla configurazione dei parametri per la connessione verso il nostro server dns, ho creato il file all'interno del nostro server  named.conf.block posizionandolo all'interno del percorso /etc/bind/dummy/ e  ho incluso il percorso del file all'interno del fine named.conf. 

Allo stato attuale in seguito al test, il comando del reload del bind va a buon fine, ma ricevo il seguente errore:

failed to write /etc/bind/dummy in DNS server IP del nostro server DNS (fopen(): Unable to open ssh2.sftp://Resource id #10//etc/bind/dummy on remote host).

Sapreste indicarmi se devo applicare qualche permesso?

**Comment by rickyb82** [comment]
Per poter consentire la scrittura nel file named.conf.block e l'applicazione delle regole al DNS sarà necessario inserire nel file named.conf la seguente stringa

 include "/etc/bind/named.conf.block";

e creare il file named.conf.block con il comando:

 touch /etc/bind/named.conf.block

e nella TAB "Zone Patch" devi mettere la path con anche il nome del file, quindi dovrai mettere: "/etc/bind/named.conf.block"

Ovviamente sto assumendo che tu le conf di bind le abbia dentro /etc/bind/
Altrimenti devi modificare il percorso con quello corretto....
