### ISSUE TITLE
Cron pulizia log e token scaduti

### ISSUE THREAD

**Issue by zhaknafein** [OpenAccess-Italia/ComplianceGuard#12]
Ciao,
stavo pensando di implementare un cron per la pulizia delle tabelle di log e token, secondo voi quanto dovrebbe essere la retention?
Le tabelle interessate sarebbero:
- `action_log` (operazioni di cron e utenti)
- `authentication_log` (autenticazione utenti)
- `ps_api_log` (log chiamate API Piracy Shield)
- `ps_api_access_tokens` (token di accesso API Piracy Shield)
- `ps_api_refresh_tokens` (token di refresh autenticazione API Piracy Shield)

Potrei mettere tutto in una schermata di settings aggiuntiva, così ognuno può impostare la retention desiderata.

**Comment by rickyb82** [comment]
Si ci stavamo pensando di mettere un rotate, si potrebbe fare come hai detto tu, ossia mettere una retention custom, se ti va puoi procedere così poi facciamo upgrade anche della VM in modo da inserire tutti gli aggiornamenti fatti.
