### ISSUE TITLE
Api smettono di funzionare

### ISSUE THREAD

**Issue by MzTechnology97** [OpenAccess-Italia/ComplianceGuard#13]
Segnalo un comportamento insolito della piattaforma.
Spesso accade che le chiamate api smettono di funzionare senza alcun motivo.
Effettuando un test manuale,  "API status" va in errore "API system is not responsive (view action log for more infos)".
Verificando i log, la chiamata API per il ping status va in errore " ping result: system is offline (connection error)".
Il tunnel IPSec è regolarmente UP.
Per far funzionare nuovamente le API, devo ogni volta recarmi sul menu di configurazione del servizio e senza effettuare nessuna variazione, salvo la configurazione e il tutto riprende a funzionare.

**Comment by rickyb82** [comment]
Le API smettono di funzionare perchè la VPN cade e strongswan non riesce a riprenderla entro i retry o la Phase2 va in stallo e strongswan va quindi in timeout, il salvataggio fa il clear e fa ripartire la sessione VPN, vi consiglio di attivare la mail in modo da avere feedback da parte della piattaforma se questo accade e di verificare che il server vpn del PS sia sempre raggiungibile dalla vostra rete. In alternativa vi consiglio di far fare la VPN dall'aparato che fa da gateway alla VM e modificare la VM nella folder /opt/src/ e fare un "chmod -x" ai file ipsec e a quello iptables, poi fare un semplice reboot.
