### ISSUE TITLE
Sezione "Manual" non funzionante

### ISSUE THREAD

**Issue by A4EVA** [OpenAccess-Italia/ComplianceGuard#14]
Salve, dopo aver importato e configurato con successo la macchina ho abilitato la sezione Manual per poter iniziare ad inserire qualche FDQN e testare il funzionamento con i miei DNS, tuttavia sembra sia inserendoli a mano che tramite file txt gli FQDN non vengono popolati. Ci sono bug / errori noti in questa sezione della piattaforma ?

**Comment by NET-REALITY** [comment]
confermo

**Comment by rickyb82** [comment]
Il DB del DNS viene aggiornato ogni 10 minuti, quindi se viene inserito un FQDN o un IP in massimo 10 minuti lo ritrovate sul server DNS.
Avete fatto il test DNS in modo che tutto sia correttamente funzionante?

**Comment by A4EVA** [comment]
Dunque, il DNS è configurato ed il test è stato eseguito dando esito positivo. La cosa strana è che nel cliccare il più, dopo aver indicato l'FQDN, non succede nulla, nella tabella sottostante non appare l'entry. Ok per quanto riguarda l'attesa necessaria per trovare gli FQDN nel server DNS ma lato piattaforma, una volta cliccato il più, i record inseriti dovrebbero apparire subito o è necessario attendere ? Per quanto riguarda l'aggiunta da file txt, aggiungo qui sotto un'immagine del comportamento della piattaforma.
![massive_add](https://github.com/OpenAccess-Italia/ComplianceGuard/assets/4736991/761a342a-2ea6-4bd7-8314-cfd0d900840c)
Grazie Infinite per il supporto !

**Comment by rickyb82** [comment]
Il modulo Manual è stato abilitato nei setting?
Compare nella dashboard come tutti i moduli attivati

**Comment by A4EVA** [comment]
Certamente, in caso contrario mi sembra che scompare proprio la sezione che permette di inserire il record

**Comment by MzTechnology97** [comment]
Confermo che anche a me la sezione manual non funziona dal primo giorno. Quando provo a inserire l'item, cliccando su + non succede nulla. Questo accade sia sugli FQDN, IPv4 e IPv6.

**Comment by rickyb82** [comment]
Ora ho capito perchè non vi funziona, non avete fatto le modifiche di questa pull 


[https://github.com/OpenAccess-Italia/ComplianceGuard/pull/9]

In caso entrate in ssh nella macchina prendete i privilegi di root con il comando

**su -** 

e poi inviate questi comandi

  **apt-get install git**
  
  **mkdir /var/lib/lxc/lamp/rootfs/var/www/git**

  **cd /var/lib/lxc/lamp/rootfs/var/www/git**

  **git clone https://github.com/OpenAccess-Italia/ComplianceGuard**

  **cp /var/lib/lxc/lamp/rootfs/var/www/git/ComplianceGuard/ps.openaccessitalia.org-main/resources/views/manual/lists/fqdn.blade.php /var/lib/lxc/lamp/rootfs/var/www/html/resources/views/manual/lists/**

  **cp /var/lib/lxc/lamp/rootfs/var/www/git/ComplianceGuard/ps.openaccessitalia.org-main/resources/views/manual/lists/ipv4.blade.php /var/lib/lxc/lamp/rootfs/var/www/html/resources/views/manual/lists/**

  **cp /var/lib/lxc/lamp/rootfs/var/www/git/ComplianceGuard/ps.openaccessitalia.org-main/resources/views/manual/lists/ipv6.blade.php /var/lib/lxc/lamp/rootfs/var/www/html/resources/views/manual/lists/**

  **cp /var/lib/lxc/lamp/rootfs/var/www/git/ComplianceGuard/ps.openaccessitalia.org-main/resources/views/piracy/whitelist.blade.php /var/lib/lxc/lamp/rootfs/var/www/html/resources/views/piracy/**

  **cp ComplianceGuard/ps.openaccessitalia.org-main/app/Http/Controllers/Admin/AdminController.php /var/lib/lxc/lamp/rootfs/var/www/html/app/Http/Controllers/Admin/**

  **cp ComplianceGuard/ps.openaccessitalia.org-main/app/Http/Controllers/Admin/DNSController.php /var/lib/lxc/lamp/rootfs/var/www/html/app/Http/Controllers/Admin/**

 **rm -r /var/lib/lxc/lamp/rootfs/var/www/git**

**Comment by rickyb82** [comment]
Posso chiudere la Issue in quanto la FIX è stata implementata e testata
