### ISSUE TITLE
Manual BGP

### ISSUE THREAD

**Issue by NET-REALITY** [OpenAccess-Italia/ComplianceGuard#16]
Salve,
provando ad inserire un IPv4 sul modulo Manual viene correttamente inviato al BGP ma rimuovendo l'IPv4 esso non viene rimosso dal BGP!!
Stessa procedura con FQDN in Manual, viene cancellato dal dns!!

Grazie

**Comment by antoniog1211** [comment]
net-reality utilizzi router mikrotik per la sessione bgp? se si pui aiutarmi per la configurazione del mikrotik con PS ?

**Comment by NET-REALITY** [comment]
> net-reality utilizzi router mikrotik per la sessione bgp? se si pui aiutarmi per la configurazione del mikrotik con PS ?

si scrivimi a; info .. netreality.it

**Comment by NET-REALITY** [comment]
messo bgpctl network flush prima del cat nel file push_net4.sh e adesso cancella correttamente.
Saluti
