### ISSUE TITLE
Supporto RPZ per Unbound e Bind

### ISSUE THREAD

**Issue by diegocanton** [OpenAccess-Italia/ComplianceGuard#17]
La VM potrebbe funzionare con un server PowerDNS, creando una zona "RPZ.local", i domini verrebbero aggiunti a questa zona e ciò potrebbe essere fatto tramite SQL o API in PowerDNS.

Digamos que devemos bloquear "listasuper.tv.iptv", adicionaria o registro "listasuper.tv.iptv.rpz.local" do tipo CNAME e valor ".", ciò causerebbe un NXDOMAIN e per il reindirizzamento utilizzare semplicemente A per un IP o CNAME con un FQDN valido.

Configura una sessione per inserire l'autorizzazione al trasferimento per l'IP degli N server DNS ricorsivi del provider.  

Adesso bastava inserire la configurazione RPZ nel Bind o Unbound dell'ISP e il gioco è fatto, ogni inserimento genererebbe un Transfer (AXFR) e il DNS lo applicherebbe immediatamente, senza bisogno di ricaricamenti o riavvii.

**Comment by NET-REALITY** [comment]
HI Diego, I use PowerDNS, plaese explain...

**Comment by giuseppeRoar** [comment]
suppongo si riferisca a questo tipo di configurazione: https://www.linuxbabe.com/ubuntu/set-up-response-policy-zone-rpz-in-bind-resolver-on-debian-ubuntu

**Comment by Antonio-Prado** [comment]
ciao,

non sarebbe proprio un issue, ma forse e' una feature request. se fai un fork di questo repository puoi provare a pubblicare la tua implementazione.

facci sapere
grazie
