### ISSUE TITLE
Manual FQDN dont work

### ISSUE THREAD

**Issue by giuseppeRoar** [OpenAccess-Italia/ComplianceGuard#19]
hello, upgraded to last version form github (vm installation).  manual FQDN doesen't  work.  pls see image:

![image](https://github.com/OpenAccess-Italia/ComplianceGuard/assets/13434403/02e91662-acc0-46d6-85eb-dab51997e39c)

**Comment by rickyb82** [comment]
[https://github.com/OpenAccess-Italia/ComplianceGuard/issues/14#issuecomment-1950237892](url)
