### ISSUE TITLE
CNCPO  PFX file do not exists

### ISSUE THREAD

**Issue by giuseppeRoar** [OpenAccess-Italia/ComplianceGuard#20]
Buongiorno,

ho inserito il nostro certificato, convertito come da comando indicato in "/opt/cert" del OS principale. Quando faccio test viene indicato  "PFX file do not exists" penso sarebbe utile creare una path univico dove inserire il certificato. 

per caso va inserito  in un path relativo al container  lamp ? 

Grazie

**Comment by giuseppeRoar** [comment]
Confermo che va inserito nel container LAMP, la cosa andrebbe indicata nella grafica.

**Comment by rickyb82** [comment]
Tutte le operazioni che si fanno per l'accesso all'applicativo, è scontato che avvengano del rootfs di lamp... non è una issue questa pertanto la chiudo
