### ISSUE TITLE
CNCPO non valida il file - mancanza verbosità nei log

### ISSUE THREAD

**Issue by giuseppeRoar** [OpenAccess-Italia/ComplianceGuard#21]
Buongiorno,

ho configurato come test il download del CNCPO con il nostro certificato (ovviamente ho fatto approvare l'indirizzo ip per il download) la password è indicata correttamente ( no spazi o altro) verificata nel .env; l'url è corretto.  da Tests dice che i setting sono ok, che il download è ok ma non supera la validazione,  è possibile vedere dei log più verbosi ?
l'unica cosa che il sistema dice è: blacklist not valid

**Comment by rickyb82** [comment]
Questo accade per due motivi: il primo la URL di download non è corretta:

Va messa in questo modo:

https://XXX.XXX.XXX.XXX/Blacklist/Download

Il secondo motivo, se non si raggiunge il sito dove scaricarla, perchè la verifica del certificato è una semplice decodifica del PFX con la password inserita e se è ok conferma che il certificato è ok, solo dopo si connette al server e cerca di scaricare il file, vi consiglio di verificare dalla VM, la corretta raggiungibilità di XXX.XXX.XXX.XXX lanciando dalla VM:

curl https://XXX.XXX.XXX.XXX/Blacklist/Download

Se risponde con errore certificato, allora il server si raggiunge correttamente, altrimenti se non risponde, vuol dire che l'indirizzo IP non è autorizzato.

**Comment by giuseppeRoar** [comment]
Buongiorno, può chiudere la issue, mancava /Blacklist/Download  in ogni caso ho verificato la doc tecnica in mio possesso e l'url /Blacklist/Download non è citato.  (documentazione aggiornata a settembre 2023 fornita dalla PP)
