### ISSUE TITLE
Sincronizzazione lista IP online

### ISSUE THREAD

**Issue by medianetsrl** [OpenAccess-Italia/ComplianceGuard#22]
Buongiorno,
se non sbaglio, l'applicazione non prende in considerazione il caso in cui un ticket venga rimosso dal PiracyShield perché inserito per errore del segnalatore, tant'è che, attualmente, la mia istanza contiene 1507 ipv4 mentre la lista online ne elenca 1503.
Mi sembra di capire che  eliminando gli ip di troppo dalla tabella ps_ipv4s non sia sufficiente e forse dovrei eliminare i ticket corrispondenti a quegli ip o magari eliminare il contenuto .
Avete suggerimenti in merito?
Grazie

**Comment by rickyb82** [comment]
Stasera procediamo a inserire update che cancellerà eventuali ticket modificati o rimossi. Aggiornerò questa issue chiudendola non appena avrò sistemato.

**Comment by medianetsrl** [comment]
Buongiorno, 
un ticket in particolare con id 8ba00f51e3524a6e8417741034f5fa7c , conteneva 3 ip che poi sono stati rimossi. Al momento non riesco a verificare ma, quell'id è ancora online, per cui credo che abbiano modificato il contenuto del ticket. Purtroppo non mi risulta che abbiano previsto un "ticket di rimozione" per cui tutto il processo risulterà un bel po' più pesante. 
Un item rimosso non necessita feedback per cui potrebbe essere più conveniente svuotare le tabelle fqdn, ipv4 e ipv6 e riempirle nuovamente usando le relative chiamate dirette piuttosto che ciclare ogni volta tutti i ticket.

**Comment by rickyb82** [comment]
Abbiamo aggiornato l'applicazione, vi consigliamo di eseguire l'update come da comandi disponibili nel readme.
Inoltre vi consigliamo di aggiornare anche gli script in quanto è richiesto il flush delle rotte sul BGP come da update di qualche settimana fa

**Comment by medianetsrl** [comment]
Chiedo scusa ma non trovo nessun file modificato nelle ultime 24 ore nell'applicazione
