### ISSUE TITLE
Errore in pagina whitelist di ps

### ISSUE THREAD

**Issue by alex1983sa** [OpenAccess-Italia/ComplianceGuard#23]
Salve a Tutti
quando tento di accedere alla pagina whitelist del modulo ps ottengo questo errore:

DataTables warning: table id=datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

qualcuno potrebbe gentilmente indicarmi da cosa dipende?

Grazie

**Comment by medianetsrl** [comment]
Buongiorno, 
ho avuto lo stesso errore con la pagina Actions Logs ed era causata da un eccesso di memoria richiesta dal php per cui ho risolto aumentando memory_limit in php.ini.
Puoi verificare se si tratta dello stesso errore controllando error.log di apache.

**Comment by alex1983sa** [comment]
Salve grazie per la risposta,
il problema era dovuto alla comunicazione con l'api una volta risolto quello e ultimata la procedura il problema si è risolto
magari potrebbe essere utile mappare quella eccezione per dare un errore più chiaro, ma ora funziona tutto

Grazie a Tutti
Alessandro
