### ISSUE TITLE
connessioe vpn down

### ISSUE THREAD

**Issue by alex1983sa** [OpenAccess-Italia/ComplianceGuard#24]
Salve a tutti,
sta capitando che la vpn dopo un po' va giu' e il server delle api non è più raggiungibile, se faccio save sui settings dopo qualche secondo risale e funziona tutto per un po' poi ricade

è capitato a qualcuno ? 

Saluti

**Comment by Antonio-Prado** [comment]
si', sembra capitare in modo generalizzato
