### ISSUE TITLE
Modifica URL reset password e creazione utente

### ISSUE THREAD

**Issue by Niubbo75** [OpenAccess-Italia/ComplianceGuard#25]
Buona sera a tutti, vorrei avere delle informazioni sulla piattaforma ComplianceGuardV1 che ho installato con successo ma sulla quale sto avendo qualche problemino di lieve importanza ma che vorrei risolvere, in pratica, quando genero un utente, la mail che viene inviata presenta un link per accedere con un FQDN che è differente da quello dove risiede la nostra VM, lo stesso vale per il link presente nella mail di reset password.
Dove posso modificare questi dettagli in modo che gli utenti possano liberamente cliccare sul link senza doverlo modificare a mano? Grazie a chiunque risponderà, complimenti per il lavoro svolto.

**Comment by medianetsrl** [comment]
Buonasera,
io non ho visto nella GUI dove si possa modificare, ma ho risolto lo stesso problema modificando APP_URL nel file .env che contiene tutti i settaggi. Il percorso è /var/lib/lxc/lamp/rootfs/var/www/html/.env

**Comment by Niubbo75** [comment]
Buona sera, molte grazie per la celere risposta, stavo per segnalare la stessa cosa, che mi hanno cortesemente indicato nel gruppo Telegram del progetto!
Buon fine settimana :-)
