### ISSUE TITLE
annunci BGP al riavvio - script    trigger_ipv46.sh

### ISSUE THREAD

**Issue by AlexIT-FT** [OpenAccess-Italia/ComplianceGuard#26]
Se riavvio la VM, il bgp non invia gli annunci, finchè non arriva una modifica.
Io ho risolto modificando lo script   trigger_ipv46.sh  modificando nelle prime l'assegnazione di LTIMEvt e LTIMEv6

```
#!/bin/bash

LTIMEv4=0
LTIMEv6=0

while true    
do
   ATIMEv4=`stat -c %Z /opt/src/ipv4.txt`
   ATIMEv6=`stat -c %Z /opt/src/ipv6.txt`

   if [[ "$ATIMEv4" != "$LTIMEv4" || "$ATIMEv6" != "$LTIMEv6" ]]
   then    
       /opt/src/push_net46.sh
       LTIMEv4=$ATIMEv4
       LTIMEv6=$ATIMEv6
   fi
   sleep 5
done
```

In pratica, forzo la prima esecuzione di **push_net46.sh** all'avvio dell script (ovvero al boot).

**Comment by Antonio-Prado** [comment]
Inserito PR, grazie
