### ISSUE TITLE
Modifica password successiva alla creazione dell'utente.

### ISSUE THREAD

**Issue by fabriziofossati** [OpenAccess-Italia/ComplianceGuard#28]
E' possibile avere una voce per la modifica password all'interno dell'utente utilizzato e nel caso la possibilità per chi fa da admin di resettare o cambiare la password degli utenti?

**Comment by rickyb82** [comment]
Non è una Issue ma una richiesta di modifica gestione che chiunque può implementarla visto che è un OpenSource.

Al momento non è previsto nessun aggiornamento al sistema gestionale degli utenti da parte di OpenAccess Italia, in quanto quello che c'è è sufficiente alla gestione del Piracy Shield.
