### ISSUE TITLE
Modifica al campo Enable plain export (CSV)

### ISSUE THREAD

**Issue by fabriziofossati** [OpenAccess-Italia/ComplianceGuard#29]
Dopo l'ultimo aggiornamento si presenta questo campo impostato su disabled e se si prova a cambiare lo stesso non viene memorizzata la modifica e si viene riportati sulla pagina iniziale dei setting.

**Comment by rickyb82** [comment]
Sincronizzare le modifiche anche nel file .env prendendole dal file .env.example come riportato nel file README
Chiudo la Issue
