### ISSUE TITLE
Dopo la conversione mi funziona benissimo, su Esxi 6.7 ma siccome l'ho passato in thick è diventato 42 GB. Lo fornisco volentieri, ma si fa molto più in fretta a convertirlo sul vmware che non a fare l'upload/download.

### ISSUE THREAD

**Issue by danp86** [OpenAccess-Italia/ComplianceGuard#3]
Ciao , ho riscontrato lo stesso problema su Esxi 6.7 , hai la possibilità di passarmi l'ovf della tua macchina in ovf?

Graie

**Comment by Antonio-Prado** [comment]
ciao,

stiamo predisponendo degli archivi piu' snelli.

ciao

**Comment by fmalfatto** [comment]
6.7 non importa l'ovf bisogna caricare il vmdk, convertirlo da sparse a thck (o thin) e poi aggiungerlo alla vm creata a parte
Potrei fare io il vmdk, ma è circa 40 GB e contiene già molte personalizzazioni, ti conviene convertirlo cl comando che ho scritto nell'altro post

**Comment by danp86** [comment]
Ciao grazie della risposta, ho fatto come era scritto nel post ed ha
funzionato, ho riscontrato un ulteriore problema , per il processo
 netowork.service restava in down , rinominando da etc/ networking il nome
della scheda di rete da en03 al nome effettivo della scheda di rete
visualizzata con ip a da terminale sulla vm, sono riuscito ad accedere all’
web page dell’app, ma inserendo le credenziali di accesso alla web app mi
appare error 500 web server. Inoltre dovrei cambiare l’indirizzo ip della
vm cambiando l’ip dal file etc/networking suppongo che non raggiungerei più
la web app. Potresti dirmi dove trovo le indicazioni per cambiare ip ?


Grazie della disponibilità





Il giorno ven 2 feb 2024 alle 17:23 fmalfatto ***@***.***> ha
scritto:

**Comment by fmalfatto** [comment]
I files interessati per riconfigurare il network sono:
/etc/network/interfaces (normale configurazione di debian)
/var/lib/lxc/lamp/rootfs/var/www/html/storage/settings/network.csv   (configurazione della app come riportato nel readme)

Io non ho toccato altro e raggiungo il web senza problemi

Se poi vuoi fare le cose eleganti, correggi anche il suggerimento degli indirizzi nel messaggio di login in /etc/issue

**Comment by danp86** [comment]
Buongiorno, 
 
oggi sto riscontrando lo stesso problema che spiegavo ieri. Raggiungo il server, accedo alla pagina di login ma una volta inserite le credenziali di accesso web , viene restituito errore 500.  Cosa può bloccare l'accesso alla web app, in seguito all'inserimento delle credenziali? posso controllare lo stato di qualche processo all'interno del server? 

![Open_Access_login](https://github.com/OpenAccess-Italia/ComplianceGuard/assets/119482806/81995733-eff4-4a86-ad87-34397fb12370)
![openaccess_italia](https://github.com/OpenAccess-Italia/ComplianceGuard/assets/119482806/4a8addb2-021e-4b02-bee7-dbee064668ec)

Grazie

**Comment by fmalfatto** [comment]
A me funziona normalmente, Non ho ancora fatto nessuna modifica alle configurazioni, ma l'interfaccia web mi sembra perfetta.
Hai provato a vedere i files di log in /var/lib/lxc/lamp/rootfs/var/log/apache2 ?

**Comment by danp86** [comment]
Buon pomeriggio,

in seguito alla corretta configurazione dell'indirizzamento ip, riesco ad accedere all'interfaccia di configurazione dell'app lavarel.
Seguendo la guida su github, procedo con la configurazione dei parametri del Piracy Shield, in seguito all'inserimento della preshared key a noi fornita da agcom, il portale dell'app non risulta più accessibile, si vede una pagina bianca.

Allego il file di log dell'app lavarel.

Eseguendo la configurazione del'smtp, il portale prende la configurazione e l'invio delle mail di test funziona in modo corretto.,

Grazie
[lavarel_log.txt](https://github.com/OpenAccess-Italia/ComplianceGuard/files/14168080/lavarel_log.txt)
