### ISSUE TITLE
VPN down

### ISSUE THREAD

**Issue by teolas98** [OpenAccess-Italia/ComplianceGuard#31]
Ciao a tutti,

capita che la VPN cada e che poi non risalga anche per qualche giorno, nonostante multipli "save" delle impostazioni e riavvii della VM.

Sta succedendo anche ad altri? C'è una souzione?

**Comment by rickyb82** [comment]
No, è un problema di raggiungibilità della rete VPN utilizzata, non è una issue del sistema. Controllate che l'ip pubblico della VPN sia raggiungibile dalla vostra rete e al massimo attivate uno script come hanno fatto in tanti che verificano la raggiungibilità della pagina http di agcom, purtroppo i loro ip non rispondono a PING e non si può fare un check ping ma solo una CURL. Chiudo Issue perchè non è un issue
