### ISSUE TITLE
VPN attiva ma server AGCOM non raggiungibili

### ISSUE THREAD

**Issue by bio761** [OpenAccess-Italia/ComplianceGuard#32]
Buongiorno, ho installato e configurato la VM, anche la parte DNS e testato con la parte ADM e funziona tutto. 
Ho finalmente ricevuto da AGCOM le credenziali per i siti di test e produzione, e anche i dati per la VPN.

Ho inserito tutti i dati, la VPN sale ma facendo il test va in KO. Mi sembra di aver capito che il problema potrebbe essere legato al cambio obbligatorio delle credenziali.
Ho provato a riconfigurare iptables sulla VM per sfruttarla come DNAT verso i server AGCOM sistemando anche la parte dei filtri, ma non riesco comunque a raggiungere i server...non riesco a capire se è un problema di configurazione mio o da parte di AGCOM (gli ip forniti non si pingano ma anche qua mi sembra di aver capito che è normale.

Avete qualche suggerimento=

Grazie,

Fabio

**Comment by fabriziofossati** [comment]
Ciao,
ti conviene fare il primo accesso con relativa cambio password manualmente e poi mettere il tutto sul server.

**Comment by bio761** [comment]
Ciao, è quello che sto provando a fare sfruttando la configurazione della VM per non dover tirare su un'altra macchina per fare la VPN...facendo questa configurazione:

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

DNAT       tcp  --  anywhere             (ip pubblico della CG)  tcp dpt:https to:ip-privato-lato"agcom"-da-agcom:443

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       all  --  anywhere             nom-host-dato-da-agcom   to:ip-privato-lato"mio"-da-agcom

quindi cercando con un DNAT e un SNAT di raggiungere AGCOM, ho poi aggiunto i filtri:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request limit: avg 30/min burst 120
ACCEPT     all  --  "mio-ip"  anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:55022 ctstate NEW,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:55080 ctstate NEW,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bgp ctstate NEW,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  -- "mio ip"  anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Ma non funziona...non capisco se sto percorrendo una strada sbagliata io o se potrebbe essere un problema di configurazione fornita da AGCOM

Grazie

**Comment by fabriziofossati** [comment]
Mi spiace ma non so dirti se questa soluzione è valida, io per raggiungere la pagina indipendentemente dalla VM per fare il primo login con cambio password ho tirato su la VPN dal pc utilizzando FortiClient e scrivendo nel file host del pc l'ip da risolvere per agcom, ovviamente mi sono dato nella connessione locale temporaneamente il pubblico che abbiamo indicato ad agcom per la VPN

**Comment by bio761** [comment]
Ho seguito il tuo approccio, mi daresti due dritte sulla configurazione del forticlient. grazie

**Comment by bio761** [comment]
sono riuscito, chiudo
