### ISSUE TITLE
Aggiornamento comunicazione CNCPO

### ISSUE THREAD

**Issue by giuseppeRoar** [OpenAccess-Italia/ComplianceGuard#33]
Buongiorno,

il cncpo il data 14.03 ha variato il metodo di comunicazione e il server "vecchio" risulta offline, c'è in programma di adeguare la piattaforma openaccess ?

**Comment by rickyb82** [comment]
Buongiorno,
la piattaforma già ora consente l'import da file nella parte manual dove basterà formattare il file CSV che l'autority invierà secondo lo standard che è richiesto nel file import. 
Quando poi si avrà il file che loro invieranno, scriveremo un breve howto su come renderlo compatibile CG.
