### ISSUE TITLE
Errore 504

### ISSUE THREAD

**Issue by AndreP78** [OpenAccess-Italia/ComplianceGuard#35]
Buongiorno, ho un problema nei refresh, spesso và in errore 504, quando capita provo con Telnet e si connette, ma random senza un timing preciso a volte si connette per la verifica dei Ticket, altre volte no. ( a volte un errore 7 ok, oppure 4 errori e poi ok)Quindi prosegue per alcuni cicli con errore poi riprende.
Idem nel refresh dei Token , a volte non riesce a farlo, ma poi procede con la verifica dei Tiket altre volte il contrario.
Quando lavora, e trova ticket, fà il suo lavoro, ma non capisco dove potrebbe essere il problema
Ringrazio  Anticipatamente
A

**Comment by rickyb82** [comment]
Non è un problema dell'app CG ma un problema delle API di PS.
