### ISSUE TITLE
Set processed ok ma forse no

### ISSUE THREAD

**Issue by medianetsrl** [OpenAccess-Italia/ComplianceGuard#37]
Ciao,
andando a controllare lo stato del PS da web gui, ho notato che i singoli item, all'interno dei ticket, non hanno lo status Processed nonostante l'applicazione CG li abbia segnati tutti come processati (anche se con forti ritardi). Non mi sembra un problema dell'applicazione ma piuttosto un problema delle API di PS, me lo confermate? succede anche ad altri?

Grazie

**Comment by rickyb82** [comment]
Tutto regolare, siamo tutti nella stessa barca.

Ciao

Riccardo

Il giorno mer 8 mag 2024 alle ore 14:56 medianetsrl <
***@***.***> ha scritto:

**Comment by medianetsrl** [comment]
Grazie per la conferma
