### ISSUE TITLE
Eliminazione Massiva lista Manuale

### ISSUE THREAD

**Issue by bio761** [OpenAccess-Italia/ComplianceGuard#38]
Buongiorno, avrei la necessità di eliminare massivamente degli FQDN inseriti per errore nella lista manuale...come posso fare?

Grazie

**Comment by bio761** [comment]
Nessuno??

**Comment by medianetsrl** [comment]
Io potrei suggerire la via della query sql. Nel file /var/www/html/.env del contenitore lamp trovi le credenziali di accesso al database

**Comment by zhaknafein** [comment]
Al momento devi farlo sul database, se stai usando l'appliance OVA puoi usare questi comandi:
```
su - 
lxc-attach lamp
grep DB_PASSWORD /var/www/html/.env # password database
mysql -u CGDB_user -p CGDB
delete from manual_fqdns where ... # query da parametrizzare a piacere
```
