### ISSUE TITLE
Come cambiare la email di un utente ed aggiungere un dns secondario?

### ISSUE THREAD

**Issue by fmalfatto** [OpenAccess-Italia/ComplianceGuard#4]
Sto cercando di creare un utente amministratore per sostituirlo ad admin. Ho visto che deve esistere l'smtp server per mandargli la password, e cercando di usare un smtp di test voglio cambiare la email dell'utente appena creato. Il campo email nella pagina edit user non è modificabile, e non trovo come cancellare l'utente e ricrearlo ex novo.
Inoltre, avendo un dns server primario e due secondari, come faccio ad aggiungere il secondario. La Gui permette un primario ed un secondario.

**Comment by juritasselli** [comment]
Non è possibile cambiare l'indirizzo mail di account già creati. Gli utenti non possono essere eliminati da gui al momento (eventualmente può eliminarlo da mysql), gli utenti possono solo essere disabilitati tramite la disattivazione del flag "Enabled".
Per testare l'invio della mail può utilizzare la funzione presente nella parte "Admin -> Tests" all'interno della tab "SMTP".
Per quanto riguarda il DNS server secondario, l'update di quest'ultimo si attiva una volta che vengono valorizzati correttamente i campi nella sezione "Admin -> Settings" all'interno delle tab  "General -> Secondary DNS".

**Comment by fmalfatto** [comment]
Grazie, provvedo a disabilitare l'account e a ricrearlo.
Per il dns ho già definito il primario e secondario dalla gui. Il problema è che abbiamo due secondari

**Comment by juritasselli** [comment]
Anche se disabilita l'account l'indirizzo mail deve essere univoco per tutti gli utenti creati, è necessario quindi che venga variata anche rispetto all'utente disabilitato.
Per adesso il sistema supporta fino a 2 DNS server.

**Comment by fmalfatto** [comment]
Perfetto. Cercherò di cancellare l'utente da mysql (non conosco come entrare in una shell lxc ma penso non sia difficile) perché mi sembra importante potere eliminare un utente a fronte di un errore, se giustamente la email deve essere univoca. 
Per il dns non è un problema, basterà usare solo primario ed un secondario.
Ogni suggerimento su come potere agire in mysql sula tabella /var/lib/lxc/lamp/rootfs/var/lib/mysql/CGDB/users è ben accetto.

**Comment by Antonio-Prado** [comment]
ciao,

semplicissimo, dall'host:
```
lxc-attach lamp
mysql -uroot -pOpenaccessItalia@2024
use CGDB;
```

fail le modifiche che credi, poi
```
/q
exit

```
e sei a posto
ciao
--
antonio

**Comment by fmalfatto** [comment]
Grande, fatto in 5 minuti, grazie!!! Con un aiuto come il vostro forse se ne esce!  :-)
