### ISSUE TITLE
Problema certificato server Piracy Shield

### ISSUE THREAD

**Issue by omelendres** [OpenAccess-Italia/ComplianceGuard#40]
Verificato errori di aggiornamento dopo che il certificato sul server Piracy Shield di Agcom è stato aggiornato.
Il problema è che debian 12 della VM non ha caricata la root CA di questo certificato.

Fatto la seguente procedura per risolvere e ha funzionato. Si accettano suggerimenti per migliorare la procedura,
```
wget http://tiTrust.crt.sectigo.com/TITrustTechnologiesOVCA.crt
openssl x509 -inform der -in TITrustTechnologiesOVCA.crt -out TITrustTechnologiesOVCA.pem


cp TITrustTechnologiesOVCA.pem /usr/local/share/ca-certificates/TITrustTechnologiesOVCA.crt
update-ca-certificates


cp /usr/local/share/ca-certificates/TITrustTechnologiesOVCA.crt /var/lib/lxc/lamp/rootfs/usr/local/share/ca-certificates/
lxc-attach lamp

update-ca-certificates
```

**Comment by AndreP78** [comment]
Confermo , con questa modifica siamo tornati Up , Grazie mille :-)

**Comment by Antonio-Prado** [comment]
aggiornato Readme con soluzione:
https://github.com/OpenAccess-Italia/ComplianceGuard/blob/main/README.md#correzione-errore-di-certificato
