### ISSUE TITLE
Portale con pagina bianca in seguito a inserimento preshared key fornita da agcom

### ISSUE THREAD

**Issue by danp86** [OpenAccess-Italia/ComplianceGuard#6]
Buon pomeriggio,

in seguito alla corretta configurazione dell'indirizzamento ip, riesco ad accedere all'interfaccia di configurazione dell'app lavarel.
Seguendo la guida su github, procedo con la configurazione dei parametri del Piracy Shield, in seguito all'inserimento della preshared key a noi fornita da agcom, il portale dell'app non risulta più accessibile, si vede una pagina bianca.

Allego il file di log del Framework lavarel.
Sembra che sul database ci sia qualche problema su datatable_white. 

Eseguendo la configurazione dell'smtp, il portale prende la configurazione e l'invio delle mail di test funziona in modo corretto.,

Grazie
[lavarel_log.txt](https://github.com/OpenAccess-Italia/ComplianceGuard/files/14168154/lavarel_log.txt)

**Comment by Antonio-Prado** [comment]
codice modificato per risolvere questo issue.

**Comment by danp86** [comment]
> codice modificato per risolvere questo issue.

Grazie della risposta, 
per poter utilizzare il compiance guard che ha la nuova parte di codice modificata, come dovrei procedere?
Ho installato l'applicativo utilizzando l'ova da voi fornito.
Vedo che il file ova non è aggiornato.
Potreste eventualmente indicarmi come aggiornare?

Grazie
