### ISSUE TITLE
VPN connection

### ISSUE THREAD

**Issue by arcocosta** [OpenAccess-Italia/ComplianceGuard#7]
Salve

sono riuscito dopo diversi passaggi a caricare la VM, estraendo il vmdk e creando una nuova macchina virtuale
configurata la rete, con nuova interfaccia rilevata ens192, cambiato IP da CLI, la pagina web funziona correttamente

modificati i valori da pagina web e inserite le configurazioni smtp, funzionanti, testate
creato nuovo utente disabilitato admin
configurato su settings dns primario e testato, me lo da funzionante, modificato il reload del servizio per usare sudo e configurato il sudo senza psw se no non funzionava il reload

ho inserito la PSK ed è andato in pagina bianca, visto le modifiche effettuate al codice risolto in un altra issue, le ho riportate, ora funziona nuovamente il web con la PSK con caratteri speciali, encoded a 64

inseriti i valori su settings: VPN peer IP, VPN remote LAN IP, VPN local LAN IP, PSK

configurato il file iptables.add per matchare la configurazione richiesta col NAT dell'indirizzo locale:

iptables -t nat -A POSTROUTING -d (VPN remote LAN IP) -j SNAT --to-source (VPN local LAN IP)

il sistema segnala errori sulla lettura ticket, più altre segnalazioni via mail,  a mio avviso non tira su neanche la VPN, nasce qui la difficoltà a capire se la VPN sta funzionando ,non trovo nessun posto dove poter verificare.

Potreste indicarmi le configurazioni complete da fare per far funzionare la VPN?
Ed eventualmente esiste un log per verificare perché la VPN non funziona?

Grazie

**Comment by rickyb82** [comment]
se nell'host mandi il comando: "ipsec status" cosa ti dice?
Hai messo anche mail-address, password e Api-URL?

**Comment by arcocosta** [comment]
ipsec status
Security Associations (0 up 0 connecting):
none

mail address e password non li ho inseriti, non capivo bene quali erano, Api-URL https://agcom.it

**Comment by danp86** [comment]
> ipsec status Security Associations (0 up 0 connecting): none
> 
> mail address e password non li ho inseriti, non capivo bene quali erano, Api-URL https://agcom.it

da documentazione AGCOM va inserito l'url fornito

**Comment by rickyb82** [comment]
Devi inserire tutto, altrimenti non funziona nulla....
La VPN senza user e password delle API e senza l'URL non serve a nulla anche perchè non pinga nessun ip, hanno messo il ping sulle API per questo motivo.
Rimuovi anche la regola delle iptables che hai messo a mano, lancia nell'host il comando: "service iptables restart"

**Comment by arcocosta** [comment]
ok mail e password trovate e inserite
iptables effettuato restart
devo modificare il file iptables.add ?
non trovo da nessuna parte l'indirizzo dell'API, dove posso recuperarlo?
sto cercando nella documentazione e nella PEC ricevuta, provo con https://agcom.it/API

**Comment by rickyb82** [comment]
Nella PEC che avete ricevuto con le credenziali di produzione c'è anche l'URL con il relativo IP che sarà quello che dovrai mettere come "Remote Vpn Lan IP" all'interno del PDF che AGcom vi ha mandato

**Comment by zhaknafein** [comment]
Occorre anche modificare la password inviata da AGCOM, accedendo la prima volta sul portale web del Piracy Shield.
Senza questo passaggio le call alle API non funzioneranno (lo vedete nei log dell'applicazione), purtroppo nel PDF non è specificato.

**Comment by Antonio-Prado** [comment]
> ok mail e password trovate e inserite iptables effettuato restart devo modificare il file iptables.add ? non trovo da nessuna parte l'indirizzo dell'API, dove posso recuperarlo? sto cercando nella documentazione e nella PEC ricevuta, provo con https://agcom.it/API

ciao,

non e' necessario modificare gli script di automazione:
- il nome dell'interfaccia viene preso automaticamente e configurata la scheda di conseguenza
- le regole di iptables vengono inserite automaticamente
- il nome host viene modificato automaticamente

ciao
--
antonio

**Comment by arcocosta** [comment]
inseriti i dati anche dell'url API, la remote VPN Lan IP gia presente e preso dal PDF.
La VPN comunque non sale, come posso debuggare il problema?

**Comment by rickyb82** [comment]
hai compilato tutti i campi? se entri in ssh nella macchina e lanci il comando: "ipsec status" cosa ti dice?
Se non sono compilati tutti i campi il file non viene salvato e quindi non sale la VPN.

**Comment by arcocosta** [comment]
si, tutti i campi della pagina Piracy Shield nei settings sono compilati

**Comment by arcocosta** [comment]
vedo anche nei log delle Action: 	trying to make piracy shield settings file in '/var/www/html/storage/settings/vpn.conf'

però il file VPN.conf dentro la cartella /var/lib/lxc/lamp/rootfs/var/www/html/storage/settings/ non viene creato

**Comment by arcocosta** [comment]
ipsec statusall:

Connections:
	agcom@ps: (IP PEER LOCALE)…(IP PEER REMOTO) IKEV2
	agcom@ps:	local: [IP_PEER_LOCALE] uses pre-shared key authentication
        agcom@ps:	remote: [IP_PEER_REMOTO] uses pre-shared key authentication
	agcom@ps:   child:  IP_LOCAL_LAN === IP_REMOTE_LAN TUNNEL
Security Associations (0 up, 0 connecting):
  None

**Comment by arcocosta** [comment]
ho provato a rifare tutto da capo, non modificando nessun file manualmente
si comporta nello stesso modo
sembra dare un errore di autenticazione, proverò a verificare la PSK con agcom:

ipsec up agcom@ps
parsed IKE_AUTH response 1 [ N(AUTH_FAILED) ] 
received AUTHENTICATION_FAILED notify error
establishing connection 'agcom@ps' failed

**Comment by rickyb82** [comment]
Stai sbagliando la configurazione della VPN, 
"VPN peer IP" ci va l'IP Pubblico che ti hanno dato dove fare la sessione VPN
"VPN remote LAN IP" ci va il loro ip che punta alla pagina da mettere su API url
"VPN local LAN IP" ci va l'ip che ti hanno assegnato loro 
"VPN pre-shared key" ci va la password che ti hanno dato

Inoltre la VPN va instaurata dall'ip pubblico che tu hai comunicato.
Se la macchina ComplianceGuard esce da quell'ip pubblico tutto funziona, altrimenti non va nulla

Ricordo inoltre di compilare anche tutti gli altri campi nella pagina di configurazione

**Comment by danp86** [comment]
> ok mail e password trovate e inserite iptables effettuato restart devo modificare il file iptables.add ? non trovo da nessuna parte l'indirizzo dell'API, dove posso recuperarlo? sto cercando nella documentazione e nella PEC ricevuta, provo con https://agcom.it/API

ho testato la connessione, l'url da utilizzare è senza /API

**Comment by Antonio-Prado** [comment]
> ho testato la connessione, l'url da utilizzare è senza /API

tutto risolto quindi?

**Comment by danp86** [comment]
Si adesso l’applicatico comunica con il portale piracyshield . Ho qualche
problema con la parte di comunicazione verso il server dns .

**Comment by rickyb82** [comment]
Per il DNS l'utente che usi per la sessione ssh deve avere i permessi per lanciare il comando di reload su bind altrimenti non funziona con un utente che non sia root.

**Comment by Antonio-Prado** [comment]
> Si adesso l’applicatico comunica con il portale piracyshield . Ho qualche problema con la parte di comunicazione verso il server dns .

ok, allora intanto questo issue lo chiudo
grazie

**Comment by danp86** [comment]
I permessi li ho assegnati e il comando di reload viene lanciato , I
problemi sono sulla scrittura

**Comment by danp86** [comment]
Dai log ho il seguente errore:

failed to write /etc/bind/named.conf.block in DNS server 185.94.135.79
(fopen(): Unable to open ssh2.sftp://Resource id
#767//etc/bind/named.conf.block on remote host)

**Comment by rickyb82** [comment]
ComplianceGuard non ha accesso in SSH alla macchina che hai messo

**Comment by danp86** [comment]
Il comando di reload riesce a inviarlo compliance

*Daniele Puglisi*

*Contatti:*

(mobile2): +39 3208128731

e-mail: ***@***.***





Il giorno ven 9 feb 2024 alle 18:43 rickyb82 ***@***.***> ha
scritto:

**Comment by danp86** [comment]
Ho anche impostato autenticazione senza password  ma con chiave rsa , e
della macchina virtuale compliance acccedo in ssh senza password al mio
server dns

*Daniele Puglisi*

*Contatti:*

(mobile2): +39 3208128731

e-mail: ***@***.***





Il giorno ven 9 feb 2024 alle 18:44 Daniele Puglisi <
***@***.***> ha scritto:

**Comment by rickyb82** [comment]
<img width="1069" alt="Screenshot 2024-02-09 alle 18 46 51" src="https://github.com/OpenAccess-Italia/ComplianceGuard/assets/71284534/a1c6bd02-59f7-4414-8a8d-0d194fae76a4">

E' simile a questa la conf?

**Comment by rickyb82** [comment]
i file di bind in che cartella sono? hai creato il file named.conf.block dentro il tuo dns?

**Comment by danp86** [comment]
Si,
Ma sul server dns , il file presente dentro la cartella bind non esiste

**Comment by danp86** [comment]
Si,

Ho creato il file de tri la cartella Bind .

Non so se debba avere una struttura predefinita il file names.conf.block
affinché compliance possa scrivere sopra
